### ISSUE TITLE
STUCK AT Starting Post-Process

### ISSUE THREAD

**Issue by jfeldhamer** [h3llrais3r/custom-scripts#1]
Everything runs but gets stuck at Starting Post-Process and no email is sent

I wrote an exe to reopen qbittorent. for Pre-Process, I had an exe close it

**Comment by h3llrais3r** [comment]
Please provide more info. Which script are you running?

**Comment by jfeldhamer** [comment]
I want qBitTorrent to open back up after the sync runs. So first I put the qBitTorrent exe in the ProcessPost variable.

That opened up qBitTorrent but then the sync script just froze. No email nothing.

So then I wrote a bat file to open qBitTorrent. I converted the bat to an exe and the same thing happened. qBitTorrent would open and the snapraid helper script would freeze

**Comment by h3llrais3r** [comment]
I suppose you're talking about snapraid helper?
Sorry, I'm not the owner of the script, I just keep it in my repo for my own usage. Not using the postProcess at all, so not able to help you here. Please raise a issue in the repo of the owner of this script.
